# .travis.yml
language: r
dist: xenial
latex: false

branches:
  only:
    - master

cache:
  packages: yes
  directories:
    - $HOME/bin

script:
  - Rscript -e 'blogdown::install_hugo()'
  - Rscript -e 'blogdown::build_site()'
  
deploy:
  - provider: pages
    script: ./deploy.sh
    skip_cleanup: true
  on:
    branch: master
  local_dir: public
  fqdn: travis-blogdown.yihui.name
