baseurl = "http://dadoszero.com.br/"
title = "Dados Zero"
languageCode = "pt-br"
defaultContentLanguage = "pt"

# Pagination
paginate = 5
paginatePath = "page"

# Theme to use
theme = "hugo-bootstrap"

[taxonomies]
  tag = "tags"
  category = "categories"

# Google analytics
# googleAnalytics = ""

[languages.en]
  languageName = "English"

  # Replace the default footer message with a localized message
  # copyright = "Hugo template made with ❤ by Xzya"
  copyright = "Dados Zero, ©Copyright 2019"

  [[languages.en.menu.main]]
    url = "/"
    name = "Home"
    weight = 1
  [[languages.en.menu.main]]
    url = "/about/"
    name = "About"
    weight = 2
  [[languages.en.menu.main]]
    url = "/contact/"
    name = "Contact"
    weight = 3
    
  [[languages.en.params]]
    mainSections = ["post"]
    
[languages.pt]
  languageName = "Português"

  # Replace the default footer message with a localized message
  # copyright = "Hugo template made with ❤ by Xzya"

  [[languages.pt.menu.main]]
    url = "/"
    name = "Home"
    weight = 1
  [[languages.pt.menu.main]]
    url = "/about/"
    name = "Sobre"
    weight = 2
  [[languages.pt.menu.main]]
    url = "/contact/"
    name = "Contato"
    weight = 3

#[languages.es]
#  languageName = "Español"

#  [[languages.es.menu.main]]
#    url = "/es/"
#    name = "Casa"
#    weight = 1
#  [[languages.es.menu.main]]
#    url = "/about/"
#    name = "Acerca de"
#    weight = 2
#  [[languages.es.menu.main]]
#    url = "/contact/"
#    name = "Contacto"
#    weight = 3

#[languages.de]
#  languageName = "Deutsch"

#  [[languages.de.menu.main]]
#    url = "/de/"
#   name = "Start"
#    weight = 1
#  [[languages.de.menu.main]]
#    url = "/about/"
#    name = "Über uns"
#    weight = 2
#  [[languages.de.menu.main]]
#   url = "/contact/"
#    name = "Kontakt"
#    weight = 3

# Links format

[permalinks]
  post = "/:year/:month/:day/:slug/"

[params]
  # Main sections (currently used for the recent posts in the sidebar)
  mainSections = ["post"]

  # Default author
  author = "Théo Albuquerque"

  # Date format (default: Jan 2, 2006)
  # date_format = "Jan 2, 2006"
   date_format = "02/01/2006"

  # Display post summaries instead of content in list templates (default: true)
  # truncate = false
  
  #Share buttons
  addThis = "ra-5c890d2ad0c54f86"
  
    # Choose a font for the social icons in the footer. Either "mono-social" or "font-awesome"
	  iconFont = "mono-social"
    # The social icons can be styled differently if you use mono as font - circle, rounded, or empty
    socialIconStyle = "circle"
    
    [social]
    twitter = "http://www.twitter.com/DadosZero"
    github = "http://www.github.com/theoadepaula/"
    linkedin = "https://www.linkedin.com/in/théo-albuquerque-de-paula-23735a156/"
  
  [params.sidebar]
    # Whether to show the recent posts or not (default: true)
    # showRecent = false

    # Whether to show the taxonomies or not (default: true)
    # showTaxonomy = false

    # How many posts to show on the sidebar (Default: 5)
    # num_recent_posts = 5
    



  [params.header]
    # Color scheme for the header (default: "light")
    # colorScheme = "dark"

  [params.footer]
    # Color scheme for the footer (default: "light")
    # colorScheme = "dark"