---
title: Tidy Tuesday - Board Games Database
author: Théo Albuquerque de Paula
date: '2019-03-12'
slug: tidy-tuesday-board-games-database
categories: []
tags:
  - tidytuesday
  - R
  - fivethirtyeight
  - Ciência de Dados
description: "Olá! Vamos utilizar o banco de dados ##fornecido## pelo projeto #TidyTuesday para ser utilizado essa semana."
---

```{r packages, echo=FALSE, warning=FALSE, message=FALSE}
pacman::p_load("tidyverse","flextable")
```


Olá! Vamos utilizar o banco de dados fornecido pelo projeto [#TidyTuesday](https://github.com/rfordatascience/tidytuesday) para ser utilizado essa semana.O banco de dados vem da [Board Game Geeks](https://boardgamegeek.com/), tendo um artigo bem interessante publicado na [FiveThirtyEight](https://fivethirtyeight.com/features/designing-the-best-board-game-on-the-planet/)

Para entender melhor o banco de dados, segue abaixo um dicionário de dados:

## Dicionário de dados
<br>
```{r dict, echo=FALSE}
dict= tibble::tribble(
               ~`Variáveis`,      ~Classe,                                                ~`Descrição`,
               "game_id", "character",                                    "Unique game identifier",
           "description", "character",                   "A paragraph of text describing the game",
                 "image", "character",                                     "URL image of the game",
           "max_players",   "integer",                               "Maximum recommended players",
          "max_playtime",   "integer",                        "Maximum recommended playtime (min)",
               "min_age",   "integer",                                   "Minimum recommended age",
           "min_players",   "integer",                               "Minimum recommended players",
          "min_playtime",   "integer",                        "Minimum recommended playtime (min)",
                  "name", "character",                                          "Name of the game",
          "playing_time",   "integer",                                          "Average playtime",
             "thumbnail", "character",                                 "URL thumbnail of the game",
        "year_published",   "integer",                                   "Year game was published",
                "artist", "character",                                       "Artist for game art",
              "category", "character",             "Categories for the game (separated by commas)",
           "compilation", "character",      "If part of a multi-compilation - name of compilation",
              "designer", "character",                                             "Game designer",
             "expansion", "character",         "If there is an expansion pack - name of expansion",
                "family", "character",                "Family of game - equivalent to a publisher",
              "mechanic", "character",    "Game mechanic - how game is played, separated by comma",
             "publisher", "character", "Comoany/person who published the game, separated by comma",
        "average_rating",    "double",                 "Average rating on Board Games Geek (1-10)",
           "users_rated",    "double",                       "Number of users that rated the game"
        )

dict %>% flextable() %>% autofit()  %>% theme_booktabs()%>% align(j=3,align = "center", part="all")

```

